- project:
    name: jluk-codi-org/zuul-jobs
    check:
      jobs:
        - testjob
        - noop

- job:
    name: testjob
    parent: base
    run: testjob.yaml
    nodeset:
      nodes:
        - name: builder
          label: centos7
