- hosts: all
  tasks:
    - debug:
        msg: Debug message.
    - debug:
        var: secret1
    - debug:
        var: hostvars
    - debug:
        msg: 'Secret: {{ hostvars["builder"]["secret1"] }}'
